### ISSUE TITLE
Just want to say THANK YOU!

### ISSUE THREAD

**Issue by creazy231** [dfabulich/service-worker-refresh-sample#1]
Just want to take the time to says THANKS! ♥
I searched around 3 full days for a method to refresh my PWApp on mobile devices after I've changed some content.
Thanks to you, my users can now install my App on their home screen and I can push updates by showing a modal to let the update the App - FINALLY!

**Comment by eugene-khyst** [comment]
@dfabulich, this sample is absolutely amazing. Very helpful. The sample is 7 years old but still I was not able to find better solution.
